'use strict';
//debugger;
var shtem = shtem || {};

shtem.C = Object.freeze({
  ITEM_STATE_ALIVE : 0,
  ITEM_STATE_DESTROYED : 1,

  //WEAPONS : 
  WEAPON_SIMPLE_GREEN_BEAM : 1,
  WEAPON_SIMPLE_RED_BEAM : 2,
  WEAPON_DOUBLE_GREEN_BEAM : 3,
  WEAPON_FOUR_GREEN_BEAM : 4,
  WEAPON_SPACE_BETWEEN_GREEN_BEAM : 5,

  //SHIPS :
  SHIP_PLAYER_1 : 1,

  //BONUS :
  BONUS_UPGRADE_SHOOT : 1,
  BONUS_HEAL : 2,

  ENNEMY_TURREL_1 : 1,
  ENNEMY_SHIP_1 : 1,

  ENNEMY_TYPE_TURREL : 1,
  ENNEMY_TYPE_SHIP : 2,
});